### ISSUE TITLE
 not compatible with other plugins

### ISSUE THREAD

**Issue by kprklg** [viroge/netbox-storage#6]
conflicts with
netbox-attachments
netbox-contract

File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: netbox_contract
Traceback (most recent call last):
  File "/opt/netbox/netbox/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/core/management/__init__.py", line 416, in execute
    django.setup()
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/netbox/venv/lib/python3.11/site-packages/django/apps/registry.py", line 93, in populate
    raise ImproperlyConfigured(

**Comment by viroge** [comment]
Installed both netbox-attachments and netbox-contract on netbox 4.1.1, no issues with the storage plugin. 
Please double check your configuration.

**Comment by viroge** [comment]
Btw did you install netbox storage via pip? It's not updated there yet. (working on it)
Until that please download netbox storage from github.

**Comment by viroge** [comment]
It's out on pip now as well, please check if the issue persists.

**Comment by kprklg** [comment]
(venv) root@nvznbxtest:/opt/netbox/netbox# pip3 install netbox-storage-plugin
Requirement already satisfied: netbox-storage-plugin in /opt/netbox/venv/lib/python3.11/site-packages (0.6.3)

(venv) root@nvznbxtest:/opt/netbox/netbox# pip3 uninstall netbox-storage-plugin
Found existing installation: netbox-storage-plugin 0.6.3
Uninstalling netbox-storage-plugin-0.6.3:
  Would remove:
    /opt/netbox/venv/lib/python3.11/site-packages/netbox_storage/*
    /opt/netbox/venv/lib/python3.11/site-packages/netbox_storage_plugin-0.6.3.dist-info/*
Proceed (Y/n)? Y
  Successfully uninstalled netbox-storage-plugin-0.6.3
(venv) root@nvznbxtest:/opt/netbox/netbox# pip3 install netbox-storage-plugin
Collecting netbox-storage-plugin
  Downloading netbox_storage_plugin-0.7.0-py3-none-any.whl.metadata (1.7 kB)
Downloading netbox_storage_plugin-0.7.0-py3-none-any.whl (19 kB)
Installing collected packages: netbox-storage-plugin
Successfully installed netbox-storage-plugin-0.7.0
(venv) root@nvznbxtest:/opt/netbox/netbox#

**Comment by kprklg** [comment]
![image](https://github.com/user-attachments/assets/a13d3c72-2d78-4699-93a9-a89fb324972c)
GOOD!!

**Comment by kprklg** [comment]
thanks
